### ISSUE TITLE
Error code: 1004. The item or resource being requested could not be found.

### ISSUE THREAD

**Issue by MrPepino** [SD4RK/epicstore_api#22]
Hello, I've started to receive this error since today:
```
Traceback (most recent call last):
  File "C:\Python\epicstore_free\main.py", line 200, in <module>
    main()
  File "C:\Python\epicstore_free\main.py", line 190, in main
    output = check_free_games()
  File "C:\Python\epicstore_free\main.py", line 29, in check_free_games
    free_games = api.get_free_games()['data']['Catalog']['searchStore']['elements']
  File "C:\Python\epicstore_free\.venv\lib\site-packages\epicstore_api\api.py", line 98, in get_free_games
    self._get_errors(data)
  File "C:\Python\epicstore_free\.venv\lib\site-packages\epicstore_api\api.py", line 483, in _get_errors
    raise EGSNotFound(
epicstore_api.exc.EGSNotFound: Error code: 1004. The item or resource being requested could not be found.
```

**Comment by TorCroft** [comment]
You can directly return `data` in method `EpicGamesStoreAPI.get_free_games`. Simply skip `self._get_errors(data)`.

``` python
def get_free_games(self, allow_countries: str = None) -> dict:
    """Returns the games from "Free Games" section in the EGS."""
    if allow_countries is None:
        allow_countries = self.country
    api_uri = (
        "https://store-site-backend-static.ak.epicgames.com/"
        "freeGamesPromotions?locale={}&country={}&allowCountries={}"
    )
    api_uri = api_uri.format(self.locale, self.country, allow_countries)
    data = self._session.get(api_uri).json()
    return data
```
I tested once, the game data returned is still normal, I don't know why there is an error `The item or resource being requested could not be found.`.

**Comment by MrPepino** [comment]
I think the issue is that empty values in the JSON response are being presented as **None** values instead of **null**.

**Comment by SD4RK** [comment]
^ Fixed with the latest commit. Looks like Epic Games messed something up like with the collections method, launcher is ignoring those errors so we probably shall too.

Closed.
